ys_blog_list:
    path:     /
    defaults: { _controller: YSBlogBundle:Default:index }

ys_blog_show:
    path:     /show/{id}
    defaults: { _controller: YSBlogBundle:Default:show }

ys_blog_edit:
    path:     /edit/{id}
    defaults: { _controller: YSBlogBundle:Default:form }

ys_blog_new:
    path:     /new
    defaults: { _controller: YSBlogBundle:Default:form }

ys_blog_delete:
    path:     /delete/{id}
    defaults: { _controller: YSBlogBundle:Default:delete }